# Dockerfile
FROM postgres:9.6

ENV POSTGRES_USER faceblock
ENV POSTGRES_PASSWORD faceblock
ENV POSTGRES_DB faceblock

# RUN mkdir -p ~/psql_data/
# COPY ./init_data.sql ~/psql_data/
# COPY ./init-user-db.sh /docker-entrypoint-initdb.d/
